name: one_click_memo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  charts_flutter: ^0.12.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1
  table_calendar: ^3.0.5
  intl: ^0.17.0
  fl_chart: ^0.55.2
  expandable: ^5.0.1
  flutter_launcher_icons: ^0.10.0
  csv: ^5.0.0
  path_provider: ^2.0.11
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:       
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true


